export const knownTechnologies: readonly string[] = [
  ".NET",
  "Agile",
  "Angular",
  "Ansible",
  "Apache Kafka",
  "AWS",
  "Azure",
  "Bash",
  "Bitbucket",
  "Bootstrap",
  "C#",
  "C++",
  "CI/CD",
  "Cypress",
  "Django",
  "Docker",
  "Drizzle ORM",
  "Elasticsearch",
  "ESLint",
  "Express.js",
  "FastAPI",
  "Figma",
  "Firebase",
  "Flask",
  "Flutter",
  "GCP",
  "Git",
  "GitHub Actions",
  "GitLab",
  "Golang",
  "GraphQL",
  "gRPC",
  "Helm",
  "Java",
  "JavaScript",
  "Jenkins",
  "Jest",
  "Jira",
  "jQuery",
  "Kotlin",
  "Kubernetes",
  "Laravel",
  "Linux",
  "Microservices",
  "Microsoft SQL Server",
  "MongoDB",
  "MySQL",
  "Nest.js",
  "Next.js",
  "Node.js",
  "NumPy",
  "Nuxt.js",
  "OAuth",
  "Pandas",
  "PHP",
  "Playwright",
  "PostgreSQL",
  "Prisma ORM",
  "Python",
  "RabbitMQ",
  "React",
  "React Native",
  "Redis",
  "Redux",
  "REST API",
  "Ruby",
  "Rust",
  "Scala",
  "SCSS",
  "Spring Boot",
  "SQL",
  "Storybook",
  "Svelte",
  "Swift",
  "Tailwind CSS",
  "Terraform",
  "TypeScript",
  "Vue.js",
  "Webpack",
  "WebSockets",
];

export const crossIndustryCompetencies: readonly string[] = [
  "Accounting",
  "AutoCAD",
  "Adobe Illustrator",
  "Adobe Photoshop",
  "Adobe InDesign",
  "Budgeting",
  "Business Development",
  "Canva",
  "Compliance",
  "Content Marketing",
  "Controlling",
  "Copywriting",
  "Customer Service",
  "Data Analysis",
  "Digital Marketing",
  "Event Management",
  "Figma",
  "Google Analytics",
  "HR Management",
  "HubSpot",
  "Inventory Management",
  "Invoicing",
  "Lean Management",
  "Logistics",
  "Microsoft Excel",
  "Microsoft Office",
  "Microsoft PowerPoint",
  "Negotiation",
  "Payroll",
  "Power BI",
  "Procurement",
  "Product Management",
  "Project Management",
  "Public Relations",
  "Quality Assurance",
  "Recruiting",
  "Reporting",
  "Risk Management",
  "SAP",
  "Salesforce",
  "SEO",
  "Six Sigma",
  "Social Media",
  "Stakeholder Management",
  "Supply Chain",
  "Tableau",
  "Team Leadership",
  "Technical Writing",
  "Training",
  "Trello",
  "UX Research",
  "Wordpress",
];

export const matchableCompetencies: readonly string[] = [
  ...knownTechnologies,
  ...crossIndustryCompetencies,
];

export const softSkillVocabulary: readonly string[] = [
  "autonomy",
  "collaboration",
  "communication",
  "leadership",
  "mentoring",
  "ownership",
  "problem solving",
  "teamwork",
  "time management",
  "eigenverantwortung",
  "kommunikation",
  "teamfähigkeit",
  "autonomie",
  "communication",
  "travail en équipe",
];

export const seniorityVocabulary: Readonly<Record<string, readonly string[]>> = {
  intern: ["intern", "internship", "praktikum", "stage"],
  junior: ["junior", "entry level", "einsteiger", "débutant"],
  mid: ["mid-level", "intermediate", "confirmé"],
  senior: ["senior", "erfahren", "expérimenté"],
  lead: ["lead", "principal", "staff", "teamleiter", "responsable"],
};

export const spokenLanguageVocabulary: Readonly<Record<string, readonly string[]>> =
  {
    English: ["english", "englisch", "anglais"],
    German: ["german", "deutsch", "allemand"],
    French: ["french", "französisch", "français"],
    Spanish: ["spanish", "spanisch", "espagnol"],
    Italian: ["italian", "italienisch", "italien"],
    Dutch: ["dutch", "niederländisch", "néerlandais"],
  };
